//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.11 at 02:59:45 AM CST 
//


package com.onboarding.hotels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for amenities complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amenities">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hotel_id_amenities" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="amenities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amenities", propOrder = {
    "hotelIdAmenities",
    "amenities"
})
public class Amenities {

    @XmlElement(name = "hotel_id_amenities")
    protected int hotelIdAmenities;
    @XmlElement(required = true)
    protected String amenities;

    /**
     * Gets the value of the hotelIdAmenities property.
     * 
     */
    public int getHotelIdAmenities() {
        return hotelIdAmenities;
    }

    /**
     * Sets the value of the hotelIdAmenities property.
     * 
     */
    public void setHotelIdAmenities(int value) {
        this.hotelIdAmenities = value;
    }

    /**
     * Gets the value of the amenities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmenities() {
        return amenities;
    }

    /**
     * Sets the value of the amenities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmenities(String value) {
        this.amenities = value;
    }

}
