//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 11:15:33 PM CST 
//


package com.onboarding.hotels;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.onboarding.hotels package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.onboarding.hotels
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetHotelByIdResponse }
     * 
     */
    public GetHotelByIdResponse createGetHotelByIdResponse() {
        return new GetHotelByIdResponse();
    }

    /**
     * Create an instance of {@link HotelDetails }
     * 
     */
    public HotelDetails createHotelDetails() {
        return new HotelDetails();
    }

    /**
     * Create an instance of {@link Amenities }
     * 
     */
    public Amenities createAmenities() {
        return new Amenities();
    }

    /**
     * Create an instance of {@link DeleteHotelByIdRequest }
     * 
     */
    public DeleteHotelByIdRequest createDeleteHotelByIdRequest() {
        return new DeleteHotelByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteHotelByIdResponse }
     * 
     */
    public DeleteHotelByIdResponse createDeleteHotelByIdResponse() {
        return new DeleteHotelByIdResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdateHotelResponse }
     * 
     */
    public UpdateHotelResponse createUpdateHotelResponse() {
        return new UpdateHotelResponse();
    }

    /**
     * Create an instance of {@link FilterHotelsByNameRequest }
     * 
     */
    public FilterHotelsByNameRequest createFilterHotelsByNameRequest() {
        return new FilterHotelsByNameRequest();
    }

    /**
     * Create an instance of {@link FilterHotelsByNameResponse }
     * 
     */
    public FilterHotelsByNameResponse createFilterHotelsByNameResponse() {
        return new FilterHotelsByNameResponse();
    }

    /**
     * Create an instance of {@link AddHotelResponse }
     * 
     */
    public AddHotelResponse createAddHotelResponse() {
        return new AddHotelResponse();
    }

    /**
     * Create an instance of {@link GetAllHotelsResponse }
     * 
     */
    public GetAllHotelsResponse createGetAllHotelsResponse() {
        return new GetAllHotelsResponse();
    }

    /**
     * Create an instance of {@link UpdateHotelRequest }
     * 
     */
    public UpdateHotelRequest createUpdateHotelRequest() {
        return new UpdateHotelRequest();
    }

    /**
     * Create an instance of {@link GetHotelByIdRequest }
     * 
     */
    public GetHotelByIdRequest createGetHotelByIdRequest() {
        return new GetHotelByIdRequest();
    }

    /**
     * Create an instance of {@link GetAllHotelsRequest }
     * 
     */
    public GetAllHotelsRequest createGetAllHotelsRequest() {
        return new GetAllHotelsRequest();
    }

    /**
     * Create an instance of {@link AddHotelRequest }
     * 
     */
    public AddHotelRequest createAddHotelRequest() {
        return new AddHotelRequest();
    }

}
